import ToggleTheme from "@/components/shared/theme-toggle";
import { TanstackProvider } from "@/providers/TanstackProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <TanstackProvider>
        <html lang="en">
          <body className="flex flex-col dark:bg-background bg-white">
            <header className="flex justify-end pt-2 pr-5">
              <ToggleTheme />
            </header>
            <main>{children}</main>
          </body>
        </html>
      </TanstackProvider>
    </ThemeProvider>
  );
}
